version: '3.8'

services:
  obs-tv-animator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: obs-tv-animator
    restart: unless-stopped
    labels:
      - "version=0.8.0"
    ports:
      - "8080:8080"
    volumes:
      # Mount media directories to allow adding content without rebuilding
      - ./animations:/app/animations:ro
      - ./videos:/app/videos:ro
      # Mount data directory for persistent state, config, and logs
      - ./data:/app/data
    environment:
      - FLASK_ENV=production
      - PORT=8080
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s